// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  $(function() {
    return $("form").on("submit", function(event) {
      var movieData, searchTerm;
      event.preventDefault();
      searchTerm = $("input").val();
      movieData = $.ajax({
        url: "http://www.omdbapi.com/",
        method: "get",
        data: {
          s: searchTerm
        },
        dataType: "json"
      });
      return movieData.done(function(data) {
        var li, movie, _i, _len, _ref;
        $("input").val("");
        $(".master").html("");
        _ref = data["Search"];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          movie = _ref[_i];
          console.log(movie.Title);
          li = $("<li> <a data-imdb=" + movie.imdbID + " href='#'>" + movie.Title + "</a> </li>");
          $(".master").append(li);
        }
        return $("a").on("click", function(event) {
          var imdbID, movieDetail;
          event.preventDefault();
          imdbID = $(event.target).data("imdb");
          movieDetail = $.ajax({
            url: "http://www.omdbapi.com/",
            method: "get",
            data: {
              i: imdbID,
              tomatoes: true,
              plot: "full"
            },
            dataType: "json"
          });
          return movieDetail.done(function(data) {
            var moviePoster, movieRating, movieSynopsis, movieTitle;
            console.log(data);
            movieTitle = $("<h1>" + data.Title + "</h1> <h2>" + data.Year + "</h2>");
            $("#title").html(movieTitle);
            moviePoster = $("<img src='" + data.Poster + "'>");
            $("#poster").html(moviePoster);
            movieRating = $("<span class='meter'>Metascore:</span> <span class='score'>" + data.Metascore + "</span> <span class='meter'>Tomato Meter:</span> <span class='score'>" + data.tomatoMeter + "</span>");
            $("#rating").html(movieRating);
            movieSynopsis = $("<p>" + data.Plot + "</p>");
            return $("#synopsis").html(movieSynopsis);
          });
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=app.map
